# Generated by Django 6.0.2 on 2026-02-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_alter_tweet_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created_at']},
        ),
    ]
